config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :list_of_posts
      get :like
      get :dislike
      get :new_comment
      post :create_new_comment
      get :show_all_comments
      get :delete_comment
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root 'users#home'
  resources :users do
    member do
      get :show
      get :send_friend_request
      get :cancel_friend_request
      get :all_friend_requests
      get :all_friends
      get :confirm
      get :reject
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

  end

  def create

  end

  def index
    @comments = Comment.all
    @current_post = Post.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>

        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<% #provide(:title, 'Sign up') %>
<div class="margin">


  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@comment,url:comments_path) do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id  %>
      <%= f.hidden_field :post_id, :value => @current_post.id%>

      <h1>  <%= f.label :Comment %></h1>
        <%= f.text_field :content%>



        <%= f.submit "Create ", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>