config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :list_of_posts
      get :like
      get :dislike
      get :new_comment
      post :create_new_comment
      get :show_all_comments
      get :delete_comment
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root 'users#home'
  resources :users do
    member do
      get :show
      get :send_friend_request
      get :cancel_friend_request
      get :all_friend_requests
      get :all_friends
      get :confirm
      get :reject
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :friend, :foreign_key => 'user_id',dependent: :destroy
  has_many :posts,  :foreign_key => 'user_id', dependent: :destroy
  has_many :friend_request, :foreign_key => 'user_id', dependent: :destroy
  has_many :statuses, :foreign_key => 'user_id', dependent: :destroy
  has_many :comments, :foreign_key => 'user_id', dependent: :destroy
  after_create :welcome_send
  before_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def welcome_send
  	CustomDeviseMailer.welcome_send(self).deliver
  end

  private
  def set_default_role
  	self.add_role :user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :confirm_password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
   @user = User.find(params[:id])
  end

  def index
    @users = User.all.page(params[:page]).per(5)
    @f= []
    @sfr  = []
    @cfr  = []
    @mt = []
    @users.each do |user|
     if current_user.id == user.id

     else
        friend = Friend.where(:user_id => current_user.id, :friend_id => user.id).first
        usr = Friend.where(:user_id => user.id, :friend_id => current_user.id).first
        if friend.nil? && usr.nil?
           fr_t = user.friend_request.where(:friend_id => current_user.id).first
           if !fr_t.nil?
              @mt.push(fr_t.user)
           else
              fr_request = current_user.friend_request.where(:friend_id => user.id).first
              if fr_request.nil?
              @sfr.push(user)
              else
              @cfr.push(user)
              end

           end

        else
          if !friend.nil?
          @f.push(user)

          else

          @f.push(user)

          end
        end
     end
    end
  end

  def all_friend_requests
    fr_req = FriendRequest.all.where(:friend_id => current_user.id)
    @frs = []
    fr_req.each do |fr|
     @frs.push(fr.user)
    end
    @frs = Kaminari.paginate_array(@frs).page(params[:page]).per(5)
  end

  def all_friends
    @fm = []
    @users = User.all
    @users.each do |user|
      if current_user.id == user.id

      else
       friend = current_user.friend.where( :friend_id => user.id).first
       usr = Friend.where(:user_id => user.id, :friend_id => current_user.id).first
       if !friend.nil?
       @fm.push(user)
       end
       if !usr.nil?
       @fm.push(user)
       end
      end
    end
    @fm = Kaminari.paginate_array(@fm).page(params[:page]).per(5)

  end

  def confirm
   fr_confirm = Friend.new(user_id:  current_user.id, friend_id: params[:id])
   if fr_confirm.save
      fr_req_s = FriendRequest.where(:user_id => params[:id], :friend_id => current_user.id).first
      if !fr_req_s.nil?
          fr_req_s.destroy
          redirect_to(root_url)
      end
   else
    flash[:notice] = "You confirmed it, Already. "
    redirect_to(root_url)
   end
  end

  def reject
   @user = User.find(params[:id])
   fr_req_s = FriendRequest.where(:user_id => params[:id], :friend_id => current_user.id).first
   if !fr_req_s.nil?
      fr_req_s.destroy
      redirect_to(root_url)
   else
      fr_req_ss = FriendRequest.where(:user_id => current_user.id, :friend_id => params[:id]).first
      fr_req_ss.destroy
      redirect_to(root_url)
    end
  end


  def send_friend_request
    @user = User.find(params[:id])
    fr_req = FriendRequest.new(user_id: current_user.id, friend_id: params[:id])
     if fr_req.save
        redirect_to(users_path)
     end
  end

  def cancel_friend_request
    fr_req_s = FriendRequest.where(:user_id => current_user.id, friend_id: params[:id]).first
    if fr_req_s.destroy
      flash[:notice] = "You have canceled friend request!!!"
      redirect_to(users_path)
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper

	 # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/all_friend_requests.html.erb
<table class="users">
 <h1>All Friend Requests</h1>
 <%= paginate @frs, :remote => true %>
 <% @frs.each do |fr| %>
   <tr>
      <td><%= gravatar_for fr %></td> <td></td>
      <td><%= fr.username %></td> <td></td>
      <td></td> <td></td>
      <td></td><td></td>
      <td><%= link_to 'Accept', confirm_user_path(fr)%></td>
      <td><%= link_to 'Reject', reject_user_path(fr)%></td>
    </tr>
  <% end %>
</table>

app/views/users/all_friends.html.erb
<div class="margin">

 <div class="col-md-6 col-md-offset-3">
<h1>All Friends</h1>
<table class="users">
<%= paginate @fm, :remote => true %>
 <% @fm.each do |user| %>
    <tr>
     <td><%= link_to gravatar_for(user, size: 50)%></td>
     <td>
       <span class="user">
         <%= link_to list_of_posts_post_path(user) do %>
        <%= user.username %>
         <% end %>
       </span>
     </td>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/users/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to The Social Site App</h1>
  <h2>
    This is the home page for Social Site  application.
  </h2>
  <% if user_signed_in? %>
  <% else %>
   <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</div>

app/views/users/index.html.erb
<table class="users">

  <h1>All Users</h1>
 <%= paginate @users %>
 <% @sfr.each do |user| %>

      <tr>
        <td><%= gravatar_for user %></td> <td></td>
        <td>
          <%= link_to list_of_posts_post_path(user) do %>
          <%= user.username %>
          <% end %>
        </td>
            <td><%= link_to 'Send Friend Request', send_friend_request_user_path(user)%></td>
      </tr>
 <%end%>
 <% @f.each do |user| %>

      <tr>
        <td><%= gravatar_for user %></td> <td></td>

        <td>
          <%= link_to list_of_posts_post_path(user) do %>
          <%= user.username %>
          <% end %>
        </td>

            <td>Friend</td>
      </tr>
 <%end%>

 <% @cfr.each do |user| %>

      <tr>
        <td><%= gravatar_for user %></td> <td></td>
        <td>
          <%= link_to list_of_posts_post_path(user) do %>
          <%= user.username %>
          <% end %>
        </td>
            <td><%= link_to 'Cancel Friend Request', cancel_friend_request_user_path(user)%></td>
      </tr>
 <%end%>

 <% @mt.each do |user| %>

      <tr>
        <td><%= gravatar_for user %></td> <td></td>
        <td>
          <%= link_to posts_path(user) do %>
          <%= user.username %>
          <% end %>
        </td>
        <td></td> <td></td>

            <!-- <td><%= link_to 'Accept', confirm_user_path(user)%></td>
             <td><%= link_to 'Reject', reject_user_path(user)%></td> -->
      </tr>
 <%end%>


</table>

app/views/users/show.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.username %>
</h1>