config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :list_of_posts
      get :like
      get :dislike
      get :new_comment
      post :create_new_comment
      get :show_all_comments
      get :delete_comment
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root 'users#home'
  resources :users do
    member do
      get :show
      get :send_friend_request
      get :cancel_friend_request
      get :all_friend_requests
      get :all_friends
      get :confirm
      get :reject
    end
  end


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :statuses, :foreign_key => 'post_id', dependent: :destroy
  has_many   :comments, :foreign_key => 'post_id', dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.all

     # render 'list_of_posts'
       # @posts = user.posts.where(:user_id => current_user.id)

  end

  def list_of_posts
    @c_user = User.find(params[:id])
    @posts = @c_user.posts.page(params[:page]).per(5)

  end


  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @post = current_user.posts.new

    # @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
   @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to list_of_posts_post_path(@post.user), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    # @post.user = current_user
    if @post.update_attributes(post_update_params)

      redirect_to list_of_posts_post_path(current_user), notice: 'Post was successfully created.'
      # format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      # format.json { render :show, status: :ok, location: @post }
    else
      redirect_to root_url
      # format.html { render :edit }
      # format.json { render json: @post.errors, status: :unprocessable_entity }
    end

  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to list_of_posts_post_path(current_user)
  end

  def like
   @po = Post.find(params[:id])
   @status = Status.new(post_id:  @po.id, user_id: current_user.id, like: true)
   if @status.save
      respond_to do |format|
        format.html { redirect_to list_of_posts_post_path(@po.user) }
        format.js
      end
    else
      respond_to do |format|
        format.html do
          flash[:notice] = "There is problem to like a post"
          redirect_to(@po)
        end
        format.js
      end

   end
  end



  def dislike
    @po = Post.find(params[:id])
     @dis = Status.all.where(:post_id => @po.id, :user_id => current_user.id, :like => true).first
    if !@dis.nil?
      if @dis.destroy
        respond_to do |format|
          format.html { redirect_to list_of_posts_post_path(@po.user) }
          format.js
        end
      else
        redirect_to(@po)
      end
    else

    end
  end

  def new_comment
    @comment = Comment.new
    @current_post = Post.find(params[:id])
  end

  def create_new_comment
    @com = current_user.comments.new(comment_params)
    if @com.save
      redirect_to(show_all_comments_post_path)
    end
  end

  def delete_comment
    @comnt = Comment.find(params[:id])
    if @comnt.destroy
      redirect_to(show_all_comments_post_path(@comnt.post))
    end
  end

  def show_all_comments

    @comment = Comment.new

    @current_post = Post.find(params[:id])
    @comments = @current_post.comments
    @post_content = @current_post.content

    if @current_post.nil?
      puts "---------------------------------------------------"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :user_id)
  end

 def post_update_params
  params.require(:post).permit(:content)
 end

  def comment_params
  params.require(:comment).permit(:content, :user_id, :post_id)
end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_dislike.html.erb
<%= link_to 'DisLike', dislike_post_path(@po), remote: true %>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(<%= like_count?(@po.id)%>)

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.hidden_field :user_id, :value => params[:id]  %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :post_content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= link_to 'Like', like_post_path(@po), remote: true %>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(<%= like_count?(@po.id)%>)

app/views/posts/_like_form.html.erb
<div class="like_form"  id= '<%= @p %>'>
<% if check_for_like?(@p)%>
    <%= render 'like' %>
<% else %>
    <%= render 'dislike' %>
<% end %>
</div>

app/views/posts/dislike.js.erb
console.log("==================================");
var m = '#' + '<%= @po.id %>'
$(m).html("<%= escape_javascript(render('posts/like')) %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for(@post) do |form| %>

  <div class="field">

    <%= form.hidden_field :user_id, :value => params[:id]  %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/like.js.erb
var m = '#' + '<%= @po.id %>'
$(m).html("<%= escape_javascript(render('posts/dislike')) %>");

app/views/posts/list_of_posts.html.erb
<p id="notice"><%= notice %></p>
<h1><%= gravatar_for @c_user %><%= @c_user.username %> &nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <% if current_user.id == @c_user.id%>
    <%= link_to 'New Post', new_post_path %>
  <% end %>
</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% if !@posts.nil?%>
    <%= paginate @posts %>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <% if current_user.id == @c_user.id || (current_user.has_role? :admin)%>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Show', show_all_comments_post_path(post) %></td>
          <% end %>
         <% cuser = @c_user%>
         <% if !(current_user.has_role? :admin) %>
           <% if check_for_friend?(cuser.id)%>
             <td><%= link_to 'Show', show_all_comments_post_path(post) %></td>
           <% end %>
         <% end %>
            <% @p = post.id %>
            <% @po = post %>
            <td><%= render 'like_form' if user_signed_in? %></td>
        </tr>
      <% end %>
    <% else%>
     <tr> <td>There is no post!!!!</td></tr>
   <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="margin">

 <div class="col-md-6 col-md-offset-3">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'All Posts', list_of_posts_post_path(current_user) %>
</div></div>

app/views/posts/new_comment.html.erb
<% #provide(:title, 'Sign up') %>
<div class="margin">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@comment,url:create_new_comment_post_path) do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id  %>
      <%= f.hidden_field :post_id, :value => @current_post.id%>
      <h1>  <%= f.label :Comment %></h1>
        <%= f.text_field :content%>
        <%= f.submit "Create ", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>

app/views/posts/show_all_comments.html.erb
<p id="notice"><%= notice %></p>
<h1>All Comments</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td> <%= @current_post.content %></td>
  </tr>
  <% if !@comments.nil? %>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= gravatar_for comment.user %><%= comment.user.username %></td>
        <td><%= comment.content %></td>
        <% if check_for_delete?(comment) || (current_user.has_role? :admin) %>
            <td><%= link_to 'Delete', delete_comment_post_path(comment) %></td>
        <% end%>
      </tr>
    <% end %>
    <tr>
      <td>
        <%= form_for(@comment,url:create_new_comment_post_path) do |f| %>
          <%= f.hidden_field :user_id, :value => current_user.id  %>
          <%= f.hidden_field :post_id, :value => @current_post.id%>
          <h3><%= f.label :Create_Comment %></h3>
          <%= f.text_field :content%>
          <%= f.submit "Create ", class: "btn btn-primary" %>
        <% end %>
      <td>
    </tr>
  <% else %>
  <% end %>
  </tbody>
</table>