config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :list_of_posts
      get :like
      get :dislike
      get :new_comment
      post :create_new_comment
      get :show_all_comments
      get :delete_comment
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root 'users#home'
  resources :users do
    member do
      get :show
      get :send_friend_request
      get :cancel_friend_request
      get :all_friend_requests
      get :all_friends
      get :confirm
      get :reject
    end
  end


end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Social Site", '#' , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_url %></li>
        <li><%= link_to "Help",   '#' %></li>

        <% if user_signed_in? %>
          <li><%= link_to(' Users', users_path) %></li>
          <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
             </a>
             <ul class="dropdown-menu">
                <li><%= link_to ' Profile', list_of_posts_post_path(current_user) %></li>

                <li class="divider"></li>
                <li><%= link_to(' Friend Request', all_friend_requests_user_path(current_user.id))%></li>

                <li class="divider"></li>
                <li><%= link_to(' Friends',  all_friends_user_path(current_user)) %></li>
                 <li class="divider"></li>
                <li><%= link_to('    Log Out', destroy_user_session_path, method: :delete) %></li>
              </ul>
           </li>
        <% else %>
         <li><%= link_to('Login', new_user_session_path)  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>

   <%= render "layouts/header" %>
   <% if notice %>
     <p class="alert alert-success"><%= notice %></p>
   <% end %>
   <% if alert %>
     <p class="alert alert-danger"><%= alert %></p>
   <% end %>
   <%= yield %>
  </body>
</html>

app/views/layouts/mailers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mailers.text.erb
<%= yield %>